version: '3'
services:

  node:
    image: node:8.16.0-alpine
    user: node
    working_dir: /home/node/app
    ports:
      - ${PORT}:${PORT}
      - ${DEBUG_NODE_PORT}:${DEBUG_NODE_PORT}
    volumes:
      - ./:/home/node/app
    environment:
      NODE_ENV: ${NODE_ENV}
      DEBUG_NODE_SERVER: ${DEBUG_NODE_SERVER}
      DEBUG_NODE_PORT: ${DEBUG_NODE_PORT}
    expose:
      - "${PORT}"
    command: "npm start"
